/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Channel {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : string,
}
export interface Message {
  'id' : bigint,
  'authorUsername' : string,
  'content' : string,
  'channelId' : bigint,
  'timestamp' : bigint,
  'authorPrincipal' : Principal,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : Message } |
  { 'err' : string };
export type Result_2 = { 'ok' : UserProfile } |
  { 'err' : string };
export type Result_3 = { 'ok' : Channel } |
  { 'err' : string };
export interface ShutdownStatus {
  'startedAt' : bigint,
  'startedBy' : string,
  'active' : boolean,
  'endsAt' : bigint,
  'reason' : string,
}
export interface UserProfile {
  'principal' : Principal,
  'username' : string,
  'joinedAt' : bigint,
  'role' : UserRole,
  'isBanned' : boolean,
  'isMuted' : boolean,
}
export type UserRole = { 'member' : null } |
  { 'admin' : null } |
  { 'owner' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'banUser' : ActorMethod<[Principal], Result>,
  'cancelShutdown' : ActorMethod<[], Result>,
  'createChannel' : ActorMethod<[string], Result_3>,
  'deleteChannel' : ActorMethod<[bigint], Result>,
  'deleteMessage' : ActorMethod<[bigint, bigint], Result>,
  'demoteUser' : ActorMethod<[Principal], Result>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMessages' : ActorMethod<[bigint, [] | [bigint]], Array<Message>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getShutdownStatus' : ActorMethod<[], ShutdownStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRegistered' : ActorMethod<[], boolean>,
  'kickUser' : ActorMethod<[Principal], Result>,
  'listChannels' : ActorMethod<[], Array<Channel>>,
  'listUsers' : ActorMethod<[], Array<UserProfile>>,
  'muteUser' : ActorMethod<[Principal], Result>,
  'promoteUser' : ActorMethod<[Principal], Result>,
  'register' : ActorMethod<[string], Result_2>,
  'sendMessage' : ActorMethod<[bigint, string], Result_1>,
  'startShutdown' : ActorMethod<[string, bigint], Result>,
  'unbanUser' : ActorMethod<[Principal], Result>,
  'unmuteUser' : ActorMethod<[Principal], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];