/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Channel = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Text,
});
export const Result_3 = IDL.Variant({ 'ok' : Channel, 'err' : IDL.Text });
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'authorUsername' : IDL.Text,
  'content' : IDL.Text,
  'channelId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'authorPrincipal' : IDL.Principal,
});
export const UserRole = IDL.Variant({
  'member' : IDL.Null,
  'admin' : IDL.Null,
  'owner' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'joinedAt' : IDL.Int,
  'role' : UserRole,
  'isBanned' : IDL.Bool,
  'isMuted' : IDL.Bool,
});
export const ShutdownStatus = IDL.Record({
  'startedAt' : IDL.Int,
  'startedBy' : IDL.Text,
  'active' : IDL.Bool,
  'endsAt' : IDL.Int,
  'reason' : IDL.Text,
});
export const Result_2 = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
export const Result_1 = IDL.Variant({ 'ok' : Message, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'banUser' : IDL.Func([IDL.Principal], [Result], []),
  'cancelShutdown' : IDL.Func([], [Result], []),
  'createChannel' : IDL.Func([IDL.Text], [Result_3], []),
  'deleteChannel' : IDL.Func([IDL.Nat], [Result], []),
  'deleteMessage' : IDL.Func([IDL.Nat, IDL.Nat], [Result], []),
  'demoteUser' : IDL.Func([IDL.Principal], [Result], []),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getMessages' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Int)],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getShutdownStatus' : IDL.Func([], [ShutdownStatus], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'kickUser' : IDL.Func([IDL.Principal], [Result], []),
  'listChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'muteUser' : IDL.Func([IDL.Principal], [Result], []),
  'promoteUser' : IDL.Func([IDL.Principal], [Result], []),
  'register' : IDL.Func([IDL.Text], [Result_2], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [Result_1], []),
  'startShutdown' : IDL.Func([IDL.Text, IDL.Nat], [Result], []),
  'unbanUser' : IDL.Func([IDL.Principal], [Result], []),
  'unmuteUser' : IDL.Func([IDL.Principal], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Channel = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Text,
  });
  const Result_3 = IDL.Variant({ 'ok' : Channel, 'err' : IDL.Text });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'authorUsername' : IDL.Text,
    'content' : IDL.Text,
    'channelId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'authorPrincipal' : IDL.Principal,
  });
  const UserRole = IDL.Variant({
    'member' : IDL.Null,
    'admin' : IDL.Null,
    'owner' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'joinedAt' : IDL.Int,
    'role' : UserRole,
    'isBanned' : IDL.Bool,
    'isMuted' : IDL.Bool,
  });
  const ShutdownStatus = IDL.Record({
    'startedAt' : IDL.Int,
    'startedBy' : IDL.Text,
    'active' : IDL.Bool,
    'endsAt' : IDL.Int,
    'reason' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  const Result_1 = IDL.Variant({ 'ok' : Message, 'err' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'banUser' : IDL.Func([IDL.Principal], [Result], []),
    'cancelShutdown' : IDL.Func([], [Result], []),
    'createChannel' : IDL.Func([IDL.Text], [Result_3], []),
    'deleteChannel' : IDL.Func([IDL.Nat], [Result], []),
    'deleteMessage' : IDL.Func([IDL.Nat, IDL.Nat], [Result], []),
    'demoteUser' : IDL.Func([IDL.Principal], [Result], []),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getMessages' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Int)],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getShutdownStatus' : IDL.Func([], [ShutdownStatus], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'kickUser' : IDL.Func([IDL.Principal], [Result], []),
    'listChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'muteUser' : IDL.Func([IDL.Principal], [Result], []),
    'promoteUser' : IDL.Func([IDL.Principal], [Result], []),
    'register' : IDL.Func([IDL.Text], [Result_2], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [Result_1], []),
    'startShutdown' : IDL.Func([IDL.Text, IDL.Nat], [Result], []),
    'unbanUser' : IDL.Func([IDL.Principal], [Result], []),
    'unmuteUser' : IDL.Func([IDL.Principal], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };