/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import {
  Actor,
  type ActorConfig,
  type ActorSubclass,
  type Agent,
  HttpAgent,
  type HttpAgentOptions,
} from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { type _SERVICE, idlFactory } from "./declarations/main.did";
export interface Some<T> {
  __kind__: "Some";
  value: T;
}
export interface None {
  __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
  return {
    __kind__: "Some",
    value: value,
  };
}
function none(): None {
  return {
    __kind__: "None",
  };
}
function isNone<T>(option: Option<T>): option is None {
  return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
  return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
  if (isNone(option)) {
    throw new Error("unwrap: none");
  }
  return option.value;
}
function candid_some<T>(value: T): [T] {
  return [value];
}
function candid_none<T>(): [] {
  return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
  return arg == null ? undefined : arg;
}
export class ExternalBlob {
  _blob?: Uint8Array<ArrayBuffer> | null;
  directURL: string;
  onProgress?: (percentage: number) => void = undefined;
  private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null) {
    if (blob) {
      this._blob = blob;
    }
    this.directURL = directURL;
  }
  static fromURL(url: string): ExternalBlob {
    return new ExternalBlob(url, null);
  }
  static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
    const url = URL.createObjectURL(
      new Blob([new Uint8Array(blob)], {
        type: "application/octet-stream",
      }),
    );
    return new ExternalBlob(url, blob);
  }
  public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
    if (this._blob) {
      return this._blob;
    }
    const response = await fetch(this.directURL);
    const blob = await response.blob();
    this._blob = new Uint8Array(await blob.arrayBuffer());
    return this._blob;
  }
  public getDirectURL(): string {
    return this.directURL;
  }
  public withUploadProgress(
    onProgress: (percentage: number) => void,
  ): ExternalBlob {
    this.onProgress = onProgress;
    return this;
  }
}
export type Result_2 =
  | {
      __kind__: "ok";
      ok: UserProfile;
    }
  | {
      __kind__: "err";
      err: string;
    };
export type Result =
  | {
      __kind__: "ok";
      ok: null;
    }
  | {
      __kind__: "err";
      err: string;
    };
export type Result_3 =
  | {
      __kind__: "ok";
      ok: Channel;
    }
  | {
      __kind__: "err";
      err: string;
    };
export interface Message {
  id: bigint;
  authorUsername: string;
  content: string;
  channelId: bigint;
  timestamp: bigint;
  authorPrincipal: Principal;
}
export interface Channel {
  id: bigint;
  name: string;
  createdAt: bigint;
  createdBy: string;
}
export type Result_1 =
  | {
      __kind__: "ok";
      ok: Message;
    }
  | {
      __kind__: "err";
      err: string;
    };
export interface UserProfile {
  principal: Principal;
  username: string;
  joinedAt: bigint;
  role: UserRole;
  isBanned: boolean;
  isMuted: boolean;
}
export enum UserRole {
  member = "member",
  admin = "admin",
  owner = "owner",
}
export interface mainInterface {
  banUser(target: Principal): Promise<Result>;
  createChannel(name: string): Promise<Result_3>;
  deleteChannel(channelId: bigint): Promise<Result>;
  deleteMessage(channelId: bigint, messageId: bigint): Promise<Result>;
  demoteUser(target: Principal): Promise<Result>;
  getMessages(channelId: bigint, since: bigint | null): Promise<Array<Message>>;
  getMyProfile(): Promise<UserProfile | null>;
  isRegistered(): Promise<boolean>;
  kickUser(target: Principal): Promise<Result>;
  listChannels(): Promise<Array<Channel>>;
  listUsers(): Promise<Array<UserProfile>>;
  muteUser(target: Principal): Promise<Result>;
  promoteUser(target: Principal): Promise<Result>;
  register(username: string): Promise<Result_2>;
  sendMessage(channelId: bigint, content: string): Promise<Result_1>;
  unbanUser(target: Principal): Promise<Result>;
  unmuteUser(target: Principal): Promise<Result>;
}
import type {
  Channel as _Channel,
  Message as _Message,
  Result as _Result,
  Result_1 as _Result_1,
  Result_2 as _Result_2,
  Result_3 as _Result_3,
  UserProfile as _UserProfile,
  UserRole as _UserRole,
} from "./declarations/main.did.d.ts";
export class Main implements mainInterface {
  constructor(
    private actor: ActorSubclass<_SERVICE>,
    private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
    private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
    private processError?: (error: unknown) => never,
  ) {}
  async banUser(arg0: Principal): Promise<Result> {
    if (this.processError) {
      try {
        const result = await this.actor.banUser(arg0);
        return from_candid_Result_n1(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.banUser(arg0);
      return from_candid_Result_n1(
        this._uploadFile,
        this._downloadFile,
        result,
      );
    }
  }
  async createChannel(arg0: string): Promise<Result_3> {
    if (this.processError) {
      try {
        const result = await this.actor.createChannel(arg0);
        return from_candid_Result_3_n3(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.createChannel(arg0);
      return from_candid_Result_3_n3(
        this._uploadFile,
        this._downloadFile,
        result,
      );
    }
  }
  async deleteChannel(arg0: bigint): Promise<Result> {
    if (this.processError) {
      try {
        const result = await this.actor.deleteChannel(arg0);
        return from_candid_Result_n1(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.deleteChannel(arg0);
      return from_candid_Result_n1(
        this._uploadFile,
        this._downloadFile,
        result,
      );
    }
  }
  async deleteMessage(arg0: bigint, arg1: bigint): Promise<Result> {
    if (this.processError) {
      try {
        const result = await this.actor.deleteMessage(arg0, arg1);
        return from_candid_Result_n1(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.deleteMessage(arg0, arg1);
      return from_candid_Result_n1(
        this._uploadFile,
        this._downloadFile,
        result,
      );
    }
  }
  async demoteUser(arg0: Principal): Promise<Result> {
    if (this.processError) {
      try {
        const result = await this.actor.demoteUser(arg0);
        return from_candid_Result_n1(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.demoteUser(arg0);
      return from_candid_Result_n1(
        this._uploadFile,
        this._downloadFile,
        result,
      );
    }
  }
  async getMessages(
    arg0: bigint,
    arg1: bigint | null,
  ): Promise<Array<Message>> {
    if (this.processError) {
      try {
        const result = await this.actor.getMessages(
          arg0,
          to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1),
        );
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.getMessages(
        arg0,
        to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1),
      );
      return result;
    }
  }
  async getMyProfile(): Promise<UserProfile | null> {
    if (this.processError) {
      try {
        const result = await this.actor.getMyProfile();
        return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.getMyProfile();
      return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
    }
  }
  async isRegistered(): Promise<boolean> {
    if (this.processError) {
      try {
        const result = await this.actor.isRegistered();
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.isRegistered();
      return result;
    }
  }
  async kickUser(arg0: Principal): Promise<Result> {
    if (this.processError) {
      try {
        const result = await this.actor.kickUser(arg0);
        return from_candid_Result_n1(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.kickUser(arg0);
      return from_candid_Result_n1(
        this._uploadFile,
        this._downloadFile,
        result,
      );
    }
  }
  async listChannels(): Promise<Array<Channel>> {
    if (this.processError) {
      try {
        const result = await this.actor.listChannels();
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.listChannels();
      return result;
    }
  }
  async listUsers(): Promise<Array<UserProfile>> {
    if (this.processError) {
      try {
        const result = await this.actor.listUsers();
        return from_candid_vec_n11(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.listUsers();
      return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
    }
  }
  async muteUser(arg0: Principal): Promise<Result> {
    if (this.processError) {
      try {
        const result = await this.actor.muteUser(arg0);
        return from_candid_Result_n1(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.muteUser(arg0);
      return from_candid_Result_n1(
        this._uploadFile,
        this._downloadFile,
        result,
      );
    }
  }
  async promoteUser(arg0: Principal): Promise<Result> {
    if (this.processError) {
      try {
        const result = await this.actor.promoteUser(arg0);
        return from_candid_Result_n1(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.promoteUser(arg0);
      return from_candid_Result_n1(
        this._uploadFile,
        this._downloadFile,
        result,
      );
    }
  }
  async register(arg0: string): Promise<Result_2> {
    if (this.processError) {
      try {
        const result = await this.actor.register(arg0);
        return from_candid_Result_2_n12(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.register(arg0);
      return from_candid_Result_2_n12(
        this._uploadFile,
        this._downloadFile,
        result,
      );
    }
  }
  async sendMessage(arg0: bigint, arg1: string): Promise<Result_1> {
    if (this.processError) {
      try {
        const result = await this.actor.sendMessage(arg0, arg1);
        return from_candid_Result_1_n14(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.sendMessage(arg0, arg1);
      return from_candid_Result_1_n14(
        this._uploadFile,
        this._downloadFile,
        result,
      );
    }
  }
  async unbanUser(arg0: Principal): Promise<Result> {
    if (this.processError) {
      try {
        const result = await this.actor.unbanUser(arg0);
        return from_candid_Result_n1(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.unbanUser(arg0);
      return from_candid_Result_n1(
        this._uploadFile,
        this._downloadFile,
        result,
      );
    }
  }
  async unmuteUser(arg0: Principal): Promise<Result> {
    if (this.processError) {
      try {
        const result = await this.actor.unmuteUser(arg0);
        return from_candid_Result_n1(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.unmuteUser(arg0);
      return from_candid_Result_n1(
        this._uploadFile,
        this._downloadFile,
        result,
      );
    }
  }
}
function from_candid_Result_1_n14(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: _Result_1,
): Result_1 {
  return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n12(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: _Result_2,
): Result_2 {
  return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n3(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: _Result_3,
): Result_3 {
  return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n1(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: _Result,
): Result {
  return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n7(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: _UserProfile,
): UserProfile {
  return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: _UserRole,
): UserRole {
  return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: [] | [_UserProfile],
): UserProfile | null {
  return value.length === 0
    ? null
    : from_candid_UserProfile_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n8(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: {
    principal: Principal;
    username: string;
    joinedAt: bigint;
    role: _UserRole;
    isBanned: boolean;
    isMuted: boolean;
  },
): {
  principal: Principal;
  username: string;
  joinedAt: bigint;
  role: UserRole;
  isBanned: boolean;
  isMuted: boolean;
} {
  return {
    principal: value.principal,
    username: value.username,
    joinedAt: value.joinedAt,
    role: from_candid_UserRole_n9(_uploadFile, _downloadFile, value.role),
    isBanned: value.isBanned,
    isMuted: value.isMuted,
  };
}
function from_candid_variant_n10(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value:
    | {
        member: null;
      }
    | {
        admin: null;
      }
    | {
        owner: null;
      },
): UserRole {
  return "member" in value
    ? UserRole.member
    : "admin" in value
      ? UserRole.admin
      : "owner" in value
        ? UserRole.owner
        : value;
}
function from_candid_variant_n13(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value:
    | {
        ok: _UserProfile;
      }
    | {
        err: string;
      },
):
  | {
      __kind__: "ok";
      ok: UserProfile;
    }
  | {
      __kind__: "err";
      err: string;
    } {
  return "ok" in value
    ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n7(_uploadFile, _downloadFile, value.ok),
      }
    : "err" in value
      ? {
          __kind__: "err",
          err: value.err,
        }
      : value;
}
function from_candid_variant_n15(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value:
    | {
        ok: _Message;
      }
    | {
        err: string;
      },
):
  | {
      __kind__: "ok";
      ok: Message;
    }
  | {
      __kind__: "err";
      err: string;
    } {
  return "ok" in value
    ? {
        __kind__: "ok",
        ok: value.ok,
      }
    : "err" in value
      ? {
          __kind__: "err",
          err: value.err,
        }
      : value;
}
function from_candid_variant_n2(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value:
    | {
        ok: null;
      }
    | {
        err: string;
      },
):
  | {
      __kind__: "ok";
      ok: null;
    }
  | {
      __kind__: "err";
      err: string;
    } {
  return "ok" in value
    ? {
        __kind__: "ok",
        ok: value.ok,
      }
    : "err" in value
      ? {
          __kind__: "err",
          err: value.err,
        }
      : value;
}
function from_candid_variant_n4(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value:
    | {
        ok: _Channel;
      }
    | {
        err: string;
      },
):
  | {
      __kind__: "ok";
      ok: Channel;
    }
  | {
      __kind__: "err";
      err: string;
    } {
  return "ok" in value
    ? {
        __kind__: "ok",
        ok: value.ok,
      }
    : "err" in value
      ? {
          __kind__: "err",
          err: value.err,
        }
      : value;
}
function from_candid_vec_n11(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: Array<_UserProfile>,
): Array<UserProfile> {
  return value.map((x) =>
    from_candid_UserProfile_n7(_uploadFile, _downloadFile, x),
  );
}
function to_candid_opt_n5(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: bigint | null,
): [] | [bigint] {
  return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
  agent?: Agent;
  agentOptions?: HttpAgentOptions;
  actorOptions?: ActorConfig;
  processError?: (error: unknown) => never;
}
export function createActor(
  canisterId: string,
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  options: CreateActorOptions = {},
): Main {
  const agent =
    options.agent ||
    HttpAgent.createSync({
      ...options.agentOptions,
    });
  if (options.agent && options.agentOptions) {
    console.warn(
      "Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.",
    );
  }
  const actor = Actor.createActor<_SERVICE>(idlFactory, {
    agent,
    canisterId: canisterId,
    ...options.actorOptions,
  });
  return new Main(actor, _uploadFile, _downloadFile, options.processError);
}
